// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ggg', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ggg', async function() {
    await driver.get("https://www.facebook.com/")
    await driver.manage().window().setRect({ width: 1050, height: 652 })
    await driver.executeScript("window.scrollTo(0,90.66666412353516)")
    await driver.executeScript("window.scrollTo(0,532)")
    await driver.executeScript("window.scrollTo(0,900)")
    {
      const element = await driver.findElement(By.css(".x1iyjqo2:nth-child(2) > .x4k7w5x .x1i10hfl"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".x6s0dn4:nth-child(2) > .x4k7w5x .x19dipnz")).click()
  })
})
